//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.AccountCustomers = new HashSet<AccountCustomer>();
            this.Drafts = new HashSet<Draft>();
        }
    
        public int AccountID { get; set; }
        public string AccountCurrency { get; set; }
        public string AccountType { get; set; }
        public string MinimumBalance { get; set; }
        public string AccounBalance { get; set; }
        public int BranchID { get; set; }
        public System.DateTime OpenDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCustomer> AccountCustomers { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual BankAccount BankAccount2 { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Draft> Drafts { get; set; }
    }
}
