//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int ChequeID { get; set; }
        public int CustomerID { get; set; }
        public int Amount { get; set; }
        public string AmountInWords { get; set; }
        public string PayeeName { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
