//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public System.DateTime CurrencyDate { get; set; }
        public double USD { get; set; }
        public double YEN { get; set; }
        public double INR { get; set; }
        public double POUND { get; set; }
        public double EURO { get; set; }
        public double RIAL { get; set; }
        public double DIRHAM { get; set; }
    }
}
