//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft
    {
        public int DraftID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SenderName { get; set; }
        public string SenderCNIC { get; set; }
        public int ReceiverAccountID { get; set; }
        public int DraftAmount { get; set; }
        public System.DateTime DraftDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int SenderBranchID { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
