//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerPrint
    {
        public int FingerPrintID { get; set; }
        public int CustomerID { get; set; }
        public string Arcs { get; set; }
        public string Whorls { get; set; }
        public string Loops { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
