//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int WalletID { get; set; }
        public string AuthKey { get; set; }
        public string WalletType { get; set; }
        public int TransactionID { get; set; }
    
        public virtual BankTransaction BankTransaction { get; set; }
    }
}
